### ISSUE TITLE
Windows paths interpreted as hex codes

### ISSUE THREAD

**Issue by niklaas** [mllg/vim-devtools-plugin#5]
Please see jalvesaq/Nvim-R#252 . Summary:

`:RLoadPackage` translates to

```
> requireNamespace("devtools"); devtools::load_all("C:\Users\me\<some folder>")
Error: '\U' used without hex digits in character string starting "C:\U"
```

A solution would be to escape `\` as discussed here: https://stackoverflow.com/questions/8425409/file-path-issues-in-r-using-windows-hex-digits-in-character-string-error

**Comment by mllg** [comment]
Thanks for reporting. I now replace backslashes with forward slashes before sending them to R. Let me know I this still does not work for you.

**Comment by niklaas** [comment]
Works like a charm. Thanks a lot.
